CREATE OR REPLACE WAREHOUSE WH_LAB
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE DB_LAB;

CREATE OR REPLACE SCHEMA CHAT_APP;

USE SCHEMA CHAT_APP;

SELECT CURRENT_WAREHOUSE(),
       CURRENT_DATABASE(),
       CURRENT_SCHEMA();

SELECT CURRENT_ROLE();

SHOW PARAMETERS LIKE 'CORTEX_ENABLED_CROSS_REGION' IN ACCOUNT;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

USE ROLE ACCOUNTADMIN;

SHOW ROLES LIKE 'CORTEX_USER';

CREATE ROLE CORTEX_USER;

USE ROLE ACCOUNTADMIN;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE CORTEX_USER;

USE ROLE CORTEX_USER;
USE DATABASE SNOWFLAKE;
SHOW SCHEMAS;
SHOW TABLES IN SCHEMA DB_LAB.PUBLIC;

-- Passe sur ton rôle
USE ROLE CORTEX_USER;

SHOW TABLES;
SELECT CURRENT_ROLE(), CURRENT_USER(), CURRENT_DATABASE(), CURRENT_SCHEMA();

CREATE TABLE test_streamlit (
    id INT,
    nom STRING
);

INSERT INTO test_streamlit VALUES (1, 'Linh'), (2, 'Test');

SELECT * FROM test_streamlit;

DROP TABLE CHATBOT;
CREATE TABLE IF NOT EXISTS CHATBOT (
conversation_id STRING,
user_name STRING,
timestamp TIMESTAMP,
role STRING,
content STRING);






